version: '3.7'
services:
  web:
    build:
      context: .
      args:
        user: ${USER}
        uid: ${UID}
    command: rails s -b 0.0.0.0
    volumes:
      - .:/home/$USER/ajax
    ports:
      - 3000:3000
    links:
      - db
    env_file:
      - .env
  db:
    image: postgres:10.3-alpine
    ports:
      - 0:5432
    env_file:
      .env
    volumes:
      - ajax-data:/var/lib/postgresql/data
volumes:
  ajax-data:
